"""Pull real DEEP-BONUS books out of the published library into the web app's dev fixture.

A deep book is one in 200,000-600,000, so `apps/plinko/scripts/import-math-books.mjs` will never find
one — it samples the head of each file. This scans for them specifically and writes a fixture the dev
client can play, which is the only way to actually WATCH a level 6-9 round without an RGS session.

    env/Scripts/python.exe games/crimson_plinko/export_deep_books.py [mode] [--levels 6,7,8,9]

Defaults to `tendrop`, which is the most extreme case worth eyeballing: the smallest entry, the
shortest spin bar (3 notches at level 1) and the longest round.

⚠️ THESE FILES ARE BIG. A level-9 book carries 5,130 authored ball outcomes — about 560 KB of compact
JSON, and roughly 1 MB for levels 6-9 together. That is why it is written compact (not pretty-printed),
why it is a SEPARATE module from `base_books.ts` (which `import-math-books.mjs` regenerates), and why
the client imports it dynamically so it never lands in the main bundle. Delete the file when you are
done looking at it.
"""

import json
import os
import sys

import zstandard

from plinko_data import DEEP_BONUS_TARGET_LEVELS

HERE = os.path.dirname(os.path.abspath(__file__))
PUBLISH = os.path.join(HERE, "library", "publish_files")
DEFAULT_OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "stake-web-sdk", "apps", "plinko", "src", "stories", "data", "deep_books.ts")
)


def scan(mode: str, wanted: set[int]) -> dict[int, dict]:
    """First book found finishing at each wanted level. Streams — the files are 60-170 MB compressed."""
    path = os.path.join(PUBLISH, f"books_{mode}.jsonl.zst")
    if not os.path.exists(path):
        sys.exit(f"no such book file: {path}")
    found: dict[int, dict] = {}
    dctx = zstandard.ZstdDecompressor()
    with open(path, "rb") as f, dctx.stream_reader(f) as r:
        buf = b""
        while wanted - found.keys():
            chunk = r.read(1 << 22)
            if not chunk:
                break
            buf += chunk
            *lines, buf = buf.split(b"\n")
            for line in lines:
                if b'"bonusRound"' not in line:
                    continue
                book = json.loads(line)
                rounds = [e for e in book["events"] if e["type"] == "bonusRound"]
                top = max(e["level"] for e in rounds)
                if top in wanted and top not in found:
                    found[top] = book
                    balls = sum(e["freeBalls"] for e in rounds)
                    print(f"  level {top}: book id={book['id']} ({balls:,} free balls)")
                    if not wanted - found.keys():
                        break
    return found


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    mode = args[0] if args else "tendrop"
    levels = set(DEEP_BONUS_TARGET_LEVELS)
    for a in sys.argv[1:]:
        if a.startswith("--levels"):
            raw = a.split("=", 1)[1] if "=" in a else sys.argv[sys.argv.index(a) + 1]
            levels = {int(x) for x in raw.split(",") if x.strip()}
    out = DEFAULT_OUT
    for a in sys.argv[1:]:
        if a.startswith("--out"):
            out = a.split("=", 1)[1] if "=" in a else sys.argv[sys.argv.index(a) + 1]

    print(f"scanning {mode} for books finishing at levels {sorted(levels)} ...")
    found = scan(mode, levels)
    missing = sorted(levels - found.keys())
    if missing:
        print(
            f"\n[!] no book finishing at level(s) {missing} in this library. If the deep strata were "
            f"spread across {list(DEEP_BONUS_TARGET_LEVELS)} after the last `make run`, re-sim first."
        )
    if not found:
        return 1

    books = [found[k] for k in sorted(found)]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(
            "// GENERATED by stake-math-sdk games/crimson_plinko/export_deep_books.py — do not edit.\n"
            "// Real deep-bonus books pulled from the published library so dev can play a level 6-9\n"
            "// round without an RGS session. Loaded ONLY via `?force=level<N>` (dynamic import, so it\n"
            "// stays out of the main bundle). Big on purpose — a level-9 book is 5,130 ball outcomes.\n"
            f"// mode={mode}  levels={sorted(found)}\n"
            "export default "
        )
        json.dump(books, f, separators=(",", ":"))
        f.write(" as const;\n")

    size = os.path.getsize(out)
    print(f"\nwrote {len(books)} book(s) -> {out}  ({size/1e6:.2f} MB)")
    print("\nnow, in apps/plinko:")
    print("  npm run dev      (no RGS session configured -> dev-local books)")
    for lvl in sorted(found):
        print(f"  http://localhost:3003/?force=level{lvl}     then press Play")
    return 0


if __name__ == "__main__":
    sys.exit(main())
